version: '3.8'
services:
  app:
    build: .
    ports:
      - '8001:8001'
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - '3307:3307'
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: 
      MYSQL_USER:
      MYSQL_PASSWORD:
